// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfVUEKM1KXrScddJ1kfYVoT0g0O4yPIys',
    appId: '1:441145504200:web:86e6b752010969baa810fd',
    messagingSenderId: '441145504200',
    projectId: 'ouaga-chap',
    authDomain: 'ouaga-chap.firebaseapp.com',
    storageBucket: 'ouaga-chap.firebasestorage.app',
    measurementId: 'G-68FRQ7MFZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn46jriuNG9ve_yCmsUdb-g15yKc4uP_k',
    appId: '1:441145504200:android:ffb86c7e6b888c86a810fd',
    messagingSenderId: '441145504200',
    projectId: 'ouaga-chap',
    storageBucket: 'ouaga-chap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBizlb0Hh25IgSVSOc17REX0Mao0dRq06M',
    appId: '1:441145504200:ios:8baf96c91cf034f0a810fd',
    messagingSenderId: '441145504200',
    projectId: 'ouaga-chap',
    storageBucket: 'ouaga-chap.firebasestorage.app',
    iosBundleId: 'bf.ouagachap.ouagaChapClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBizlb0Hh25IgSVSOc17REX0Mao0dRq06M',
    appId: '1:441145504200:ios:8baf96c91cf034f0a810fd',
    messagingSenderId: '441145504200',
    projectId: 'ouaga-chap',
    storageBucket: 'ouaga-chap.firebasestorage.app',
    iosBundleId: 'bf.ouagachap.ouagaChapClient',
  );
}
