// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT6eV9wiOEAqunalu7Oj6bsA-c5RvimEM',
    appId: '1:464512136513:android:8668aa14c37fb4386bddc0',
    messagingSenderId: '464512136513',
    projectId: 'ouaga-chap-a888e',
    authDomain: 'ouaga-chap-a888e.firebaseapp.com',
    storageBucket: 'ouaga-chap-a888e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT6eV9wiOEAqunalu7Oj6bsA-c5RvimEM',
    appId: '1:464512136513:android:8668aa14c37fb4386bddc0',
    messagingSenderId: '464512136513',
    projectId: 'ouaga-chap-a888e',
    storageBucket: 'ouaga-chap-a888e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBueqG0lKCoUm--WidQYHJ2OI_DPY-QXMo',
    appId: '1:464512136513:ios:4b6c7b6e3b5472706bddc0',
    messagingSenderId: '464512136513',
    projectId: 'ouaga-chap-a888e',
    storageBucket: 'ouaga-chap-a888e.firebasestorage.app',
    iosBundleId: 'bf.ouagachap.ouagaChapClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBueqG0lKCoUm--WidQYHJ2OI_DPY-QXMo',
    appId: '1:464512136513:ios:4b6c7b6e3b5472706bddc0',
    messagingSenderId: '464512136513',
    projectId: 'ouaga-chap-a888e',
    storageBucket: 'ouaga-chap-a888e.firebasestorage.app',
    iosBundleId: 'bf.ouagachap.ouagaChapClient',
  );
}
